FROM grafana/grafana:6.5.2

COPY datasource.yml /etc/grafana/provisioning/datasources/datasource.yml
COPY dashboard.yml /etc/grafana/provisioning/dashboards/dashboard.yml
COPY dashboard.json /etc/grafana/provisioning/dashboards/dashboard.json
COPY defaults.ini /usr/share/grafana/conf/defaults.ini
